---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zijbfhit/public_html
    - /bin/cp -a * $DEPLOYPATH
    - /bin/cp -a .htaccess $DEPLOYPATH
    - /usr/local/bin/composer install --no-dev --optimize-autoloader --working-dir=$DEPLOYPATH
    - cd $DEPLOYPATH && /usr/local/bin/npm install
    - cd $DEPLOYPATH && /usr/local/bin/npm run build
    - cd $DEPLOYPATH && /usr/local/bin/php artisan migrate --force
